apiVersion: v1
kind: Service
metadata:
  name: fe-gateway
  labels:
    run: fe-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: website-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
  labels:
    app: website-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-app
  template:
    metadata:
      labels:
        app: website-app
    spec:
      containers:
      - name: website-app
        image: website
        ports:
        - containerPort: 80


